/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { ArrowRight, Clock3, HeartHandshake, MapPin, Menu, Phone, Sparkles, Star, UsersRound } from 'lucide-react';
import { PublicLeadForm } from '@/components/website/public-lead-form';
import { serviceSlug } from '@/lib/public-site/service-slug';
import type { getPublicBusinessSite } from '@/lib/public-site/server';

type Site = NonNullable<Awaited<ReturnType<typeof getPublicBusinessSite>>>;

export function RebuiltPublicSite({ site }: { site: Site }) {
  const { settings, account, services, team, portal } = site;
  const bookingHref = settings.show_booking && portal?.booking_enabled ? '/portal?book=1' : '#contacto';
  const currency = new Intl.NumberFormat('pt-PT', { style: 'currency', currency: account.default_currency || 'EUR' });
  const featured = services.filter((service) => !service.coming_soon).slice(0, 6);
  return <div className="min-h-screen bg-[#f5f2ec] text-[#17231d]" style={{ '--brand': settings.primary_color, '--ink': settings.accent_color } as React.CSSProperties}>
    <header className="sticky top-0 z-50 border-b border-black/5 bg-[#f5f2ec]/90 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-[90rem] items-center justify-between px-5 sm:px-8">
        <Link href="/" className="flex items-center gap-3 font-semibold tracking-tight">{account.logo_url ? <img src={account.logo_url} alt="" className="size-10 rounded-full object-contain" /> : <span className="grid size-10 place-items-center rounded-full bg-[var(--ink)] text-sm text-white">{account.name.slice(0, 1)}</span>}<span>{account.name}</span></Link>
        <nav className="hidden items-center gap-7 text-sm text-black/60 lg:flex"><a href="#experiencias">Experiências</a><a href="#metodo">O método</a><a href="#equipa">Equipa</a><a href="#contacto">Contacto</a></nav>
        <div className="flex items-center gap-2"><Link href="/portal" className="hidden rounded-full px-4 py-2 text-sm font-medium sm:block">Área do cliente</Link><Link href={bookingHref} className="inline-flex items-center gap-2 rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-semibold text-white">Marcar <ArrowRight className="size-4" /></Link><Menu className="size-5 lg:hidden" /></div>
      </div>
    </header>
    <main>
      <section className="mx-auto grid max-w-[90rem] overflow-hidden px-5 pt-5 sm:px-8 lg:grid-cols-[1.08fr_.92fr]">
        <div className="flex min-h-[620px] flex-col justify-end bg-[var(--ink)] p-8 text-white sm:p-14 lg:min-h-[720px]">
          <span className="mb-auto inline-flex w-fit items-center gap-2 rounded-full border border-white/20 px-3 py-1.5 text-xs tracking-wide uppercase"><Sparkles className="size-3" />{settings.hero_badge || 'Bem-estar com intenção'}</span>
          <p className="mb-5 max-w-md text-sm leading-6 text-white/60">{settings.hero_subtitle || 'Um tempo seu, guiado por cuidado, escuta e presença.'}</p>
          <h1 className="max-w-[9ch] text-5xl leading-[.9] font-medium tracking-[-.07em] sm:text-7xl">{settings.hero_title}</h1>
          <div className="mt-10 flex flex-wrap items-center gap-4"><Link href={bookingHref} className="rounded-full bg-[var(--brand)] px-6 py-3.5 font-semibold">Encontrar a sessão ideal</Link><a href="#experiencias" className="text-sm font-semibold text-white/80 underline underline-offset-8">Explorar experiências</a></div>
        </div>
        <div className="relative min-h-[420px] bg-stone-300 lg:min-h-[720px]">{settings.hero_image_url ? <img src={settings.hero_image_url} alt="Ambiente da clínica" className="absolute inset-0 size-full object-cover" /> : <div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_18%,var(--brand),transparent_45%),linear-gradient(140deg,#dfd5c6,#7f9785)]" />}<div className="absolute right-6 bottom-6 max-w-[16rem] rounded-2xl bg-white/85 p-5 backdrop-blur"><p className="text-xs tracking-[.16em] text-black/45 uppercase">Uma pausa real</p><p className="mt-2 text-sm leading-6">Escolha o seu momento e acompanhe tudo através do Portal do Cliente.</p></div></div>
      </section>
      <section id="metodo" className="mx-auto max-w-[90rem] px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--brand)] uppercase">Como funciona</p><h2 className="mt-4 max-w-sm text-4xl leading-tight font-medium tracking-[-.05em]">Cuidado claro, do primeiro clique ao último detalhe.</h2></div><ol className="grid gap-4 sm:grid-cols-3">{[['01','Escolha'],['02','Reserve'],['03','Acompanhe']].map(([number,title])=><li key={number} className="border-t border-black/15 pt-5"><span className="text-sm text-[var(--brand)]">{number}</span><h3 className="mt-9 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-black/55">{title === 'Escolha' ? 'Conheça cada modalidade antes de decidir.' : title === 'Reserve' ? 'Veja disponibilidade de profissional e horário.' : 'Receba confirmações e gerencie a sua sessão.'}</p></li>)}</ol></div></section>
      {settings.show_services && featured.length > 0 && <section id="experiencias" className="bg-white px-5 py-24 sm:px-8"><div className="mx-auto max-w-[90rem]"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--brand)] uppercase">Experiências</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em]">O que o seu corpo pede hoje?</h2></div><Link href="#contacto" className="text-sm font-semibold underline underline-offset-8">Precisa de ajuda a escolher?</Link></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl bg-black/10 sm:grid-cols-2 lg:grid-cols-3">{featured.map((service)=><article key={service.id} className="group relative min-h-80 bg-[#fbfaf7] p-7"><p className="text-xs font-semibold tracking-widest text-[var(--brand)] uppercase">{service.coming_soon ? 'Em breve' : `${service.duration_minutes} min`}</p><h3 className="mt-14 max-w-[11ch] text-2xl leading-tight font-medium tracking-[-.04em]">{service.name}</h3><p className="mt-4 line-clamp-3 max-w-sm text-sm leading-6 text-black/55">{service.public_presentation || service.description || 'Uma experiência preparada para o seu bem-estar.'}</p><div className="absolute right-7 bottom-7 left-7 flex items-center justify-between"><span className="font-semibold">{Number(service.price) ? currency.format(Number(service.price)) : 'Sob consulta'}</span><Link href={`/servicos/${serviceSlug(service.name)}`} className="grid size-10 place-items-center rounded-full bg-[var(--ink)] text-white transition group-hover:scale-110"><ArrowRight className="size-4" /></Link></div></article>)}</div></div></section>}
      <section className="mx-auto grid max-w-[90rem] gap-10 px-5 py-24 sm:px-8 lg:grid-cols-2"><div className="rounded-[2rem] bg-[var(--brand)] p-9 text-white sm:p-12"><HeartHandshake className="size-8" /><h2 className="mt-16 max-w-md text-4xl leading-tight font-medium tracking-[-.05em]">{settings.about_title}</h2><p className="mt-5 max-w-lg leading-8 text-white/80">{settings.about_text || 'Cada sessão começa por escutar o que precisa e termina com uma sensação de cuidado que continua consigo.'}</p></div><div className="flex flex-col justify-center"><p className="text-xs font-bold tracking-[.18em] text-[var(--brand)] uppercase">Em boas mãos</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em]">Pessoas, não apenas horários.</h2><p className="mt-5 max-w-xl leading-8 text-black/60">A sua experiência é pessoal. Por isso, pode conhecer quem está consigo e escolher com confiança.</p>{settings.show_team && team.length > 0 && <div className="mt-9 flex flex-wrap gap-3">{team.slice(0,4).map(person=><Link key={person.id} href={`/profissionais/${encodeURIComponent(person.professional_public_slug || person.id)}`} className="flex items-center gap-3 rounded-full border border-black/10 bg-white px-3 py-2 pr-5"><span className="grid size-9 place-items-center overflow-hidden rounded-full bg-stone-200">{person.avatar_url ? <img src={person.avatar_url} alt="" className="size-full object-cover" /> : <UsersRound className="size-4" />}</span><span className="text-sm font-semibold">{person.full_name}</span></Link>)}</div>}</div></section>
      {settings.show_testimonials && settings.testimonials.length > 0 && <section className="bg-[var(--ink)] px-5 py-24 text-white sm:px-8"><div className="mx-auto max-w-[90rem]"><p className="text-xs font-bold tracking-[.18em] text-white/50 uppercase">Palavras de quem viveu</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{settings.testimonials.slice(0,3).map((item,index)=><figure key={`${item.name}-${index}`} className="rounded-2xl border border-white/15 p-7"><Star className="size-4 fill-[var(--brand)] text-[var(--brand)]" /><blockquote className="mt-8 text-xl leading-8">“{item.quote}”</blockquote><figcaption className="mt-8 text-sm text-white/60">{item.name}{item.role ? ` · ${item.role}` : ''}</figcaption></figure>)}</div></div></section>}
      <section id="contacto" className="bg-white px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-[90rem] gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--brand)] uppercase">Contacto</p><h2 className="mt-4 text-4xl font-medium tracking-[-.05em]">Vamos encontrar o seu melhor momento.</h2><div className="mt-10 space-y-4 text-sm text-black/60">{settings.contact_phone && <p className="flex items-center gap-3"><Phone className="size-4 text-[var(--brand)]" />{settings.contact_phone}</p>}{settings.address && <p className="flex items-center gap-3"><MapPin className="size-4 text-[var(--brand)]" />{settings.address}</p>}{settings.opening_hours && <p className="flex items-center gap-3"><Clock3 className="size-4 text-[var(--brand)]" />{settings.opening_hours}</p>}</div></div><PublicLeadForm slug={settings.slug} primaryColor={settings.primary_color} /></div></section>
    </main>
    <footer className="bg-[#111914] px-5 py-10 text-white/65 sm:px-8"><div className="mx-auto flex max-w-[90rem] flex-wrap justify-between gap-4 text-sm"><span className="font-semibold text-white">{account.name}</span><span>© {new Date().getFullYear()} · Privacidade e cuidado em cada contacto.</span></div></footer>
  </div>;
}
